name: Push On Main
on: push
jobs:
  Print-Branch-Name:
    runs-on: ubuntu-latest
    steps:
      - name: Print-Branch-Name
        run: echo "Main Branch"
      - name: Print-My-Name
        run: echo "Mohamed Nasr"
